# Generated by Django 4.2.20 on 2025-03-10 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['flow', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='FormFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('journey_type', models.CharField(choices=[('LEAD', 'Lead'), ('DEMO_USER', 'Demo User'), ('LIVE_USER', 'Live User')], default='LEAD', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'White Labels',
            },
        ),
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_type', models.CharField(choices=[('LEAD', 'Lead'), ('DEMO_USER', 'Demo User'), ('LIVE_USER', 'Live User')], default='LEAD', max_length=50)),
                ('is_upgrade_journey', models.BooleanField(default=False, help_text='Indicates if this journey is part of an upgrade process (DEMO→LIVE)')),
                ('is_complete', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='signup_form.flowstep')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_journeys', to='signup_form.formflow')),
                ('previous_journey', models.ForeignKey(blank=True, help_text='Previous journey in an upgrade flow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_journey', to='signup_form.userjourney')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'flow')},
            },
        ),
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField()),
                ('ui_schema', models.JSONField(blank=True, help_text='Optional UI schema for customizing form rendering and behavior', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('white_label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_schemas', to='signup_form.whitelabel')),
            ],
        ),
        migrations.AddField(
            model_name='formflow',
            name='white_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_flows', to='signup_form.whitelabel'),
        ),
        migrations.AddField(
            model_name='flowstep',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='signup_form.formflow'),
        ),
        migrations.AddField(
            model_name='flowstep',
            name='form_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_steps', to='signup_form.formschema'),
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('flow_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='signup_form.flowstep')),
                ('form_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='signup_form.formschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to=settings.AUTH_USER_MODEL)),
                ('user_journey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='signup_form.userjourney')),
            ],
            options={
                'unique_together': {('flow_step', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='flowstep',
            unique_together={('flow', 'step_number')},
        ),
    ]
