# Generated by Django 4.2.20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formflow',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='formresponse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='formschema',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userjourney',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='whitelabel',
            options={'ordering': ['name'],
                     'verbose_name_plural': 'White Labels'},
        ),
        migrations.AlterUniqueTogether(
            name='userjourney',
            unique_together={('user', 'flow', 'journey_type')},
        ),
    ]
