# Generated by Django 4.2.20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_form', '0002_alter_formflow_options_alter_formresponse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='total_score',
            field=models.FloatField(
                default=0.0, help_text='Total calculated score for this form response'),
        ),
    ]
